name: ac-microcourses
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6,<3.12
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - ipython
  - ipykernel
  - jinja2
  - paho-mqtt
  - matplotlib
  - conda-forge::pymongo
  # DEVELOPMENT ONLY PACKAGES
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - sphinx