name: ac-microcourses
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - numpy
  - scipy
  - pandas
  - tqdm
  - click
  - ipython
  - ipykernel
  - jinja2
  - paho-mqtt
  - matplotlib
  - pip:
     - -e .  # install git checkout of ac-microcourses in editable mode
     # add here only pip-packages that are not available in conda/conda-forge! E.g.:
     - pyscaffold[all]
     - black[jupyter] # not sure if this syntax works for conda

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - sphinx
  - pandoc
